use serde::Deserialize;

use crate::wire::image_url::ImageUrl;

/// An image generated by an OpenAI-compatible chat model.
///
/// Providers normalise generated images into `message.images` and
/// `delta.images`. Extra provider fields such as `index`, `type`, and
/// `image_url.detail` are intentionally ignored during deserialisation.
#[derive(Debug, Clone, Deserialize)]
pub struct GeneratedImage {
    pub image_url: ImageUrl,
}
