//! Skip generated and minified files.

/// True when `relative` or `source` looks generated or minified.
pub fn generated(relative: &str, source: &str) -> bool {
    let folded = relative.to_ascii_lowercase();
    if folded.contains(".generated.")
        || folded.contains(".auto.")
        || folded.contains("/generated/")
        || folded.contains("_generated.")
        || folded.contains(".min.")
        || folded.contains("/dist/")
        || folded.ends_with(".pb.go")
        || folded.ends_with(".pb.rs")
        || folded.ends_with(".pb.cc")
        || folded.ends_with(".grpc.go")
        || folded.ends_with(".g.dart")
        || folded.ends_with(".freezed.dart")
        || folded.ends_with(".min.js")
        || folded.ends_with(".min.css")
        || folded.ends_with(".bundle.js")
        || folded.ends_with(".d.ts")
    {
        return true;
    }
    if !source.is_empty() {
        let line_count = source.lines().count().max(1);
        let average = source.len() / line_count;
        if average > 300 && line_count < 20 {
            return true;
        }
    }
    let first: String = source.lines().take(5).collect::<Vec<_>>().join(" ");
    let first = first.to_ascii_lowercase();
    first.contains("generated by")
        || first.contains("auto-generated")
        || first.contains("do not edit")
        || first.contains("code generated by")
        || first.contains("automatically generated")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn path_patterns_are_generated() {
        assert!(generated("lib/generated/api.rs", "fn x() {}"));
        assert!(generated("types.pb.go", "package api"));
        assert!(generated("client.d.ts", "export {}"));
        assert!(!generated("lib/api.rb", "class API\nend\n"));
    }

    #[test]
    fn minified_source_is_generated() {
        let source = format!("{}\n", "x".repeat(400));
        assert!(generated("app.js", &source));
    }

    #[test]
    fn generation_marker_is_generated() {
        assert!(generated(
            "schema.rs",
            "// Code generated by protoc. DO NOT EDIT.\nfn main() {}\n"
        ));
    }
}
